criaCartao('Fanfic Bob Esponja', 'Qual é o nome da sua fanfic favorita de Bob Esponja?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Quem é o seu personagem favorito de Bob Esponja para escrever fanfic?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Já escreveu alguma fanfic de Bob Esponja? Sobre o que era?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Quais outros personagens além do Bob Esponja aparecem em suas fanfics?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você já imaginou um crossover de Bob Esponja com outras séries em suas fanfics?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Qual o gênero da sua fanfic favorita de Bob Esponja?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você prefere escrever fanfics de Bob Esponja com finais felizes ou tristes?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Qual é o enredo mais maluco que você já escreveu em uma fanfic de Bob Esponja?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você já escreveu uma fanfic que envolvia um romance entre dois personagens de Bob Esponja?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Quais são os temas recorrentes nas suas fanfics de Bob Esponja?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você costuma explorar a amizade entre Bob Esponja e Patrick nas suas fanfics?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Que tipo de aventura você coloca Bob Esponja e seus amigos em suas fanfics?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Qual seria um final perfeito para uma fanfic de Bob Esponja?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você já escreveu alguma fanfic em que o Sr. Siriguejo tem um papel importante?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'O que você acha das fanfics de Bob Esponja que exploram o lado sombrio dos personagens?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você já misturou elementos de outros universos, como o de “Avatar” ou “Harry Potter”, em suas fanfics de Bob Esponja?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Em suas fanfics, como você imagina que seria o mundo fora da Fenda do Biquíni?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você tem uma fanfic de Bob Esponja que é mais focada em ação ou mais em comédia?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você gosta de explorar a vida dos personagens quando não estão no trabalho, como na Krusty Krab?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Qual a sua opinião sobre as fanfics de Bob Esponja que reimaginam o personagem como um herói?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Como você descreveria um dia perfeito para Bob Esponja em uma de suas fanfics?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você já escreveu sobre um romance inesperado entre dois personagens de Bob Esponja?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você já usou os vilões, como o Plankton, como protagonistas em suas fanfics?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Em suas fanfics, qual seria o maior desafio que Bob Esponja enfrentaria?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você já escreveu uma fanfic onde o Bob Esponja troca de corpo com outro personagem?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Qual seria o papel de Sandy Cheeks em uma história mais dramática de Bob Esponja?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você prefere escrever fanfics de Bob Esponja em formato de diálogos ou com mais descrições?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você já usou a ideia de um “universo alternativo” em alguma fanfic de Bob Esponja?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'O que você acha da ideia de um romance entre Bob Esponja e a Sra. Puff?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Como você acredita que seria uma fanfic em que todos os personagens de Bob Esponja se transformam em super-heróis?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você já escreveu uma fanfic que focava mais na relação entre o Bob Esponja e o Squidward?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você já pensou em escrever uma fanfic sobre a infância dos personagens de Bob Esponja?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Em suas fanfics, qual personagem de Bob Esponja tem um papel mais importante: Bob Esponja ou Patrick?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Como você imagina uma situação de crise para os personagens de Bob Esponja em uma fanfic?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você já escreveu sobre uma história em que o Bob Esponja perde sua esponja por um motivo sério?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Que tipo de humor você costuma usar nas suas fanfics de Bob Esponja?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Quais são as características dos personagens de Bob Esponja que você mais gosta de explorar nas fanfics?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você já escreveu alguma fanfic com temática de mistério envolvendo o Bob Esponja?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Qual é o cenário mais interessante em que você já colocou os personagens de Bob Esponja em uma fanfic?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Como você faz para manter a personalidade dos personagens de Bob Esponja nas suas fanfics?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Qual é a maior reviravolta que você já escreveu em uma fanfic de Bob Esponja?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você já pensou em escrever uma fanfic de Bob Esponja baseada em uma obra literária clássica?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Qual personagem de Bob Esponja você acha que seria o mais complicado de escrever em uma fanfic?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você gosta de escrever fanfics de Bob Esponja que envolvem viagens no tempo?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Como você descreveria a evolução de um personagem secundário em uma fanfic de Bob Esponja?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você já escreveu alguma fanfic que tenha uma moral ou lição no final?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Se você pudesse criar uma nova temporada de Bob Esponja em formato de fanfic, o que aconteceria?', 'Resposta:')
criaCartao('Fanfic Bob Esponja', 'Você já escreveu sobre a ideia de Bob Esponja sendo desafiado por um novo personagem?', 'Resposta:')